### PR TITLE
Casting values to the right types in migrator functions

### LINKED ISSUE #84: ERROR: function migrator_9699fddfa8(integer, integer, integer) does not exist
A new version of HammerDB brought forward another bug, the migration function gets made with the primary key types.
If these primary keys consist of smallints or bigints, postgresql cannot find the right function.

The error in the title is what I get when trying to migrate a table with integers and a smallint as the primary key.
Error_migrator_function

I fixed this by casting the values to the type the function was made with. I'll make a pull request.

### PR DESCRIPTION
**Pull request by NGRichter**
Additionally, when migrating during load the last migration can return no record (in my case (,,,) for 4 primary key columns). QuantumDB did not handle this, now it checks if there are no return values and breaks.

fixes #84

### CODE REVIEW

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java [hunk 1]
```diff
@@ -229,6 +233,11 @@ else if (c == '"' && prev != '\\') {
 
 		Map<String, Object> identity = Maps.newHashMap();
 		List<Column> primaryKeyColumns = from.getPrimaryKeyColumns();
+
+		if (parts.size() != primaryKeyColumns.size()) {
```
Comment (NGRichter) [inline quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java:237]: If a table only has 1 primary key, it will return () when no record is returned, this will result in parts being empty while primaryKeyColumns.size() equals 1.
Additionally if (,,,) is returned for 4 primary key columns it will only parse as 3 empty values, therefore 3 != 4 and will return nothing.

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/MigratorFunction.java [hunk 2]
```diff
@@ -12,7 +12,7 @@
 	}
 
 	private final String name;
-	private final List<String> parameters;
+	private final Map<String, String> parameters;
```
Comment (michaeldejong) [inline quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/MigratorFunction.java:15]: You probably always want this to be a `LinkedHashMap` to guarantee ordering.

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java (hunk 1 above)
Comment (michaeldejong) [reply quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java:237]: Can you clarify this one? 

- A table can at most only have one primary key. Did you mean a PK with just one column?
- When this method is called, there's always a record. Did you mean that perhaps `result` might be an empty string? If that's the case this change makes sense.

**Review by michaeldejong — APPROVED** [review]
Just a quick question, but the code looks 👍

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/MigratorFunction.java (hunk 2 above)
Comment (NGRichter) [reply quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/MigratorFunction.java:15]: I'll change it:thumbsup:

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java (hunk 1 above)
Comment (NGRichter) [reply quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java:237]: Ah yes, I keep saying 1, 2, 3 or 4 primary keys. What I mean is 1 primary key with that many columns.

Result might be "empty" (consisting of a string with only comma's) if the migration function tries to migrate data that was recently deleted by clients using the database. HammerDB inserts/updates/deletes a lot of entries, that is when I noticed this bug.

The result can be the following strings: 
"()" for a primary key with 1 column.
"(,)" for a primary key with 2 columns.
"(,,)" for a primary key with 3 columns.
...

The function will remove the brackets and then split everything on the comma's that are not escaped. But the function also includes the check to see if the last value is more than length 0. If it is not it will exclude it from the list (I think this might be a bug on its own). All columns in a primary key can never be NULL so I thought that it would be fine to check if the sizes of both lists (primary key columns and the returned values) would be equal, but I think a varchar primary key column can include the empty string "" as a value making that a possible bug.

Comment (michaeldejong) [reply quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java:237]: I'm trying to think of what situation could cause one of these cases. I suppose an empty string could result in this, but I doubt HammerDB creates records with such PK values (so that might not be the reason). The change seems logical, I'm just a bit worried we're missing something / not fully understand it.

**Comment by michaeldejong** [comment]
Haven't found a use case that runs into this issue, but the change by itself makes sense. Is this ready for merging?

**Comment by NGRichter** [comment]
Yes, this code is ready for merging, I am running a branch that consolidates all of these pull requests and everything is working fine.

The case I had when this happened was when I was running HammerDB 4.1 (they changed the data types of columns from numeric(x,y) to normal types (integer, bigint, smallint)) while forking the following changeset.
```
	<changeset id="various_operations" author="Nick Richter">
		<description>Add a new tax column to order_line, rename ol_amount to ol_amount_b and rename table orders to orders_2</description>
		<operations>
			<addColumn tableName="order_line">
				<column name="ol_tax" type="numeric" defaultExpression="0" nullable="false"/>
			</addColumn>
			<alterColumn tableName="order_line" columnName="ol_amount" newColumnName="ol_amount_b"/>
			<renameTable oldTableName="orders" newTableName="orders_2"/>
		</operations>
	</changeset>
```
PostgreSQL should still select the function but it does not (https://www.postgresql.org/docs/current/typeconv-func.html).
Some posts on internet having the same issue: https://stackoverflow.com/questions/49129211/a-function-call-misbehaves-in-postgresql https://github.com/jOOQ/jOOQ/issues/5264
