### PR TITLE
Bug fixes

### LINKED ISSUE #90: Sql tag splits every two rows/enters
The XmlMapper class splits the sql tag every two rows, this causes QuantumDB to only execute the first two rows.
Example:
```
<changeset author="Nick Richter" id="update-columns">
    <operations>
        <sql>
            UPDATE "table1" SET "column1" = '1' WHERE "column1" = 'test' AND "column2" = 'test2';
            UPDATE "table1" SET "column3" = '3' WHERE "column3" = 'test' AND "column2" = 'test2';	
            UPDATE "table2" SET "column1" = '1' WHERE "column1" = 'test' AND "column2" = 'test2';	
            UPDATE "table2" SET "column3" = '3' WHERE "column3" = 'test' AND "column2" = 'test2';	
            UPDATE "table3" SET "column1" = '1' WHERE "column1" = 'test' AND "column2" = 'test2';
            UPDATE "table3" SET "column3" = '3' WHERE "column3" = 'test' AND "column2" = 'test2';
        </sql>
    </operations>
</changeset>
```
Only the first 2 rows are rewritten and executed.

I found this StackOverflow question which describes the problem: https://stackoverflow.com/questions/11950828/read-multiple-lines-from-xml
I'll make a pull request with changes that will fix this problem.

### PR DESCRIPTION
**Pull request by NGRichter**
SAXParser calls the characters() function per 2 lines, this caused the SQL operation to only execute the first 2 lines, this fixes #90 

Additionally, when a tab character \t was placed before a keyword such as UPDATE or FROM, the table would not be rewritten into the correct table name.

Another bug was the dropping of an index when you had not specified the columns in the exact order. When a column was renamed that was part of an index it would also change places in the arraylist and it could not be found.

In SQL, single quotes \' are for string literals, while double quotes \" are used for case-sensitive tables or columns. This was not correct in the query rewriter.

### CODE REVIEW

File: quantumdb-cli/src/main/java/io/quantumdb/cli/xml/XmlMapper.java [hunk 1]
```diff
@@ -75,7 +75,20 @@ public void characters(char[] ch, int start, int length) {
...
+							if (stack.size() > 1) {
+								XmlElement grandParent = stack.get(stack.size() - 2);
+								grandParent.getChildren().remove(parent);
+								grandParent.getChildren().add(element);
+							}
+							stack.remove(parent);
+						}
+						else {
+							parent.getChildren().add(element);
+						}
```
Comment (NGRichter) [inline quantumdb-cli/src/main/java/io/quantumdb/cli/xml/XmlMapper.java:91]: Took me a whole afternoon to arrive at this solution. Other solutions where a StringBuilder was used to append strings and make 1 new XmlElement in the endElement function caused errors.

File: quantumdb-query-rewriter/src/main/java/io/quantumdb/query/rewriter/PostgresqlQueryRewriter.java [hunk 2]
```diff
@@ -51,31 +51,32 @@ public String rewrite(String query) throws SQLException {
...
+					if (onStack != null && onStack.equals(currentCharacter)) {
+						state.stack.removeFirst();
+					}
+					else {
+						state.stack.addFirst(currentCharacter);
+					}
+					processWordStartOrMiddle(state);
+					break;
+				case ' ':
+				case '\t':
```
Comment (NGRichter) [inline quantumdb-query-rewriter/src/main/java/io/quantumdb/query/rewriter/PostgresqlQueryRewriter.java:68]: Maybe \n (line breaks) should also be included, but I am not sure as I have not tested it.

File: quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java [hunk 3]
```diff
@@ -116,7 +116,7 @@ public boolean containsIndex(Collection<String> columns) {
 		checkArgument(!columns.isEmpty(), "You must specify at least one entry in 'columns'.");
 
 		return indexes.stream()
-				.anyMatch(c -> c.getColumns().equals(Lists.newArrayList(columns)));
+				.anyMatch(c -> Sets.newHashSet(c.getColumns()).equals(Sets.newHashSet(columns)));
```
Comment (NGRichter) [inline quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java:119]: Order of columns might change when a column name has been changed.

File: quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java [hunk 4]
```diff
@@ -101,7 +101,7 @@ else if (parent != null && this.parent == null) {
 
 	public Table addIndex(Index index) {
 		checkArgument(index != null, "You must specify an 'index'.");
-		checkState(!containsIndex(index.getIndexName()), "Table already contains an index with name: " + index.getIndexName());
+		checkState(!containsIndex(index.getColumns()), "Table already contains an index: " + index.getIndexName() + " with columns: " + index.getColumns());
```
Comment (NGRichter) [inline quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java:104]: containsIndex only accepts columns, and you do not want the same index (name)

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java [hunk 5]
```diff
@@ -334,11 +334,13 @@ else if (indexTableName.startsWith("\"public\".")) {
 					parser.consume();
 				}
 
-				List<String> groups = parser.consumeGroup('(', ')', ',').stream().map(String::trim).collect(Collectors.toList());
+				List<String> groups = parser.consumeGroup('(', ')', ',').stream().map(String::trim).map(CatalogLoader::removeOuterQuotes).collect(Collectors.toList());
```
Comment (NGRichter) [inline quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java:337]: Index columns were saved with quotes

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java [hunk 6]
```diff
@@ -334,11 +334,13 @@ else if (indexTableName.startsWith("\"public\".")) {
...
 				// TODO: Add support for expressions. Now we only support column references.
 
 				Table table = catalog.getTable(indexTableName);
-				table.addIndex(new Index(indexName, groups, unique));
+				if (!table.containsIndex(groups)) {
+					table.addIndex(new Index(indexName, groups, unique));
+				}
```
Comment (NGRichter) [inline quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java:343]: I ran a changelog with 50 changesets, at the end the tables all contained between 10 and 20 indexes with the same column.

File: quantumdb-postgresql/src/test/java/io/quantumdb/core/backends/integration/multistate/MultiStateTest.java [hunk 7]
```diff
@@ -79,4 +80,9 @@ public void testMigratingOverDataChange() throws MigrationException, SQLExceptio
 		migrator.drop(step1.getId());
 	}
 
+	@After
+	public void dropDatabase() {
+		super.after();
+	}
```
Comment (NGRichter) [inline quantumdb-postgresql/src/test/java/io/quantumdb/core/backends/integration/multistate/MultiStateTest.java:86]: The database did not get dropped after a test

File: quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java (hunk 4 above)
Comment (michaeldejong) [reply quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java:104]: But the name isn't based on the columns per se. You could have multiple indices on the same columns, but with different names right?

File: quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java (hunk 3 above)
Comment (michaeldejong) [reply quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java:119]: Yup, fair enough.

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java (hunk 6 above)
Comment (michaeldejong) [reply quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java:343]: Was the name different every time?

File: quantumdb-query-rewriter/src/main/java/io/quantumdb/query/rewriter/PostgresqlQueryRewriter.java (hunk 2 above)
Comment (michaeldejong) [reply quantumdb-query-rewriter/src/main/java/io/quantumdb/query/rewriter/PostgresqlQueryRewriter.java:68]: For now I'd suggest to leave it out then.

File: quantumdb-query-rewriter/src/main/java/io/quantumdb/query/rewriter/PostgresqlQueryRewriter.java [hunk 8]
```diff
@@ -131,19 +132,19 @@ private String processWord(State state, String word) throws SQLException {
...
 			}
 
-			if (tableName == null) {
-				//throw new SQLException("No table with name: '" + word + "' exists.");
-			}
-			else {
+			if (tableName != null) {
 				word = tableName;
 			}
+//			else {
```
Comment (michaeldejong) [inline quantumdb-query-rewriter/src/main/java/io/quantumdb/query/rewriter/PostgresqlQueryRewriter.java:138]: Feel free to drop this, no need to keep commented code in like this.

**Review by michaeldejong — APPROVED** [review]
Code looks good, but I'm wondering about the changes to `addIndex()`. Let me know what your thoughts are.

**Comment by michaeldejong** [comment]
Sorry that took a while to review. 😞

File: quantumdb-core/src/main/java/io/quantumdb/core/migration/operations/AlterColumnMigrator.java [hunk 9]
```diff
@@ -50,8 +50,8 @@ public void migrate(Catalog catalog, RefLog refLog, Version version, AlterColumn
 			}
 		});
 
-		operation.getHintsToDrop().stream().forEach(column::dropHint);
-		operation.getHintsToAdd().stream().forEach(column::addHint);
+		operation.getHintsToDrop().forEach(column::dropHint);
+		operation.getHintsToAdd().forEach(column::addHint);
```
Comment (NGRichter) [inline quantumdb-core/src/main/java/io/quantumdb/core/migration/operations/AlterColumnMigrator.java:54]: .stream() does not guarantee it will be executed in order: https://www.baeldung.com/java-collection-stream-foreach

File: quantumdb-core/src/main/java/io/quantumdb/core/migration/operations/DropColumnMigrator.java [hunk 10]
```diff
@@ -30,7 +30,9 @@ public void migrate(Catalog catalog, RefLog refLog, Version version, DropColumn
 
 		List<Index> indexes = Lists.newArrayList(table.getIndexes());
 		for (Index index : indexes) {
-			table.removeIndex(index.getColumns());
+			if (index.getColumns().contains(operation.getColumnName())) {
+				table.removeIndex(index.getColumns());
+			}
```
Comment (NGRichter) [inline quantumdb-core/src/main/java/io/quantumdb/core/migration/operations/DropColumnMigrator.java:35]: It would drop all indexes when a column was dropped, now it will only drop the indexes that had the column.

File: quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java [hunk 11]
```diff
@@ -101,29 +101,35 @@ else if (parent != null && this.parent == null) {
...
+		return containsIndex(Lists.newArrayList(columns));
 	}
 
-	public boolean containsIndex(Collection<String> columns) {
+	public boolean containsIndex(List<String> columns) {
 		checkArgument(!columns.isEmpty(), "You must specify at least one entry in 'columns'.");
 
 		return indexes.stream()
-				.anyMatch(c -> Sets.newHashSet(c.getColumns()).equals(Sets.newHashSet(columns)));
+				.anyMatch(i -> i.getColumns().equals(columns));
```
Comment (NGRichter) [inline quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java]: I made a mistake in believing column ordering in indexes are not important, it is, so everything is converted to a list.

File: quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java [hunk 12]
```diff
@@ -133,14 +139,14 @@ public Index removeIndex(Collection<String> columns) {
 	}
 
 	public Index getIndex(String... columns) {
-		return getIndex(Sets.newHashSet(columns));
+		return getIndex(Lists.newArrayList(columns));
 	}
 
-	public Index getIndex(Collection<String> columns) {
+	public Index getIndex(List<String> columns) {
```
Comment (NGRichter) [inline quantumdb-core/src/main/java/io/quantumdb/core/schema/definitions/Table.java:145]: Might be important to also specify if the index should be unique or not. But I am not sure what the added value would be when specifying two indexes on a table with the same order of columns with one unique and the other not.

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java [hunk 13]
```diff
@@ -316,7 +316,7 @@ private static void addIndexes(Connection connection, Catalog catalog, String ta
 				parser.present("CONCURRENTLY");
 				String indexName = parser.consume();
 				indexName = removeOuterQuotes(indexName);
-				if (indexName.startsWith("pk_")) {
+				if (indexName.endsWith("_pkey")) {
```
Comment (NGRichter) [inline quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/CatalogLoader.java:319]: Primary key indexes end with "_pkey". Before this change, all indexes made by primary key constraints were duplicated.

File: quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java [hunk 14]
```diff
@@ -157,7 +157,7 @@ private String stripEscaping(String parameterName) {
 				if (resultSet.next()) {
 					Map<String, Object> id = Maps.newHashMap();
 					for (String primaryKeyColumn : primaryKeyColumns) {
-						Object value = resultSet.getObject(primaryKeyColumn);
+						Object value = parseValue(from.getColumn(primaryKeyColumn).getType().getType(),resultSet.getObject(primaryKeyColumn).toString());
```
Comment (NGRichter) [inline quantumdb-postgresql/src/main/java/io/quantumdb/core/planner/TableDataMigrator.java:160]: It would throw an error that it could not compare the postgres type with the java type, this will parse it into the compatible type.

**Comment by NGRichter** [comment]
Sorry for the delay, I had been writing my thesis as the deadline for the concept version was last Sunday.
I did my validation testing on my local machine which includes all the changes above.

File: quantumdb-core/src/main/java/io/quantumdb/core/migration/operations/AlterColumnMigrator.java (hunk 9 above)
Comment (michaeldejong) [reply quantumdb-core/src/main/java/io/quantumdb/core/migration/operations/AlterColumnMigrator.java:54]: True, but if it does a `.forEachOrdered()` can be used which does support this. The change itself is 👍 though

**Review by michaeldejong — APPROVED** [review]
Changes look good to me.

> Sorry for the delay, I had been writing my thesis as the deadline for the concept version was last Sunday.

Nice! Crossing my fingers for a good result. 👍
